Update to README.md
olivia-ai/olivia pull request #139
Opened 2020-11-09 16:14 UTC by A-Yamout

- Update to README.md 
- I added 

```bash
$ cd ~
$ cd olivia/
```
To make it easier to install it for beginners in Linux
- Does not fix any Issues but I am working on a fix in the README.md for issue 102

2020-11-17 08:21 UTC, hugolgst requested changes

2020-11-17 08:21 UTC, hugolgst commented on README.md
> +$ cd ~
Not sure this step is neccesary

2020-11-18 18:59 UTC, A-Yamout commented on README.md
> +$ cd ~
Could you explain please

2020-11-19 08:29 UTC, hugolgst commented on README.md
> +$ cd ~
This step is not neccesary

2020-11-19 19:29 UTC, closed without merging